### ISSUE TITLE
Api.test.ts does not seem to test anything

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#76] opened 2021-05-19 09:40 UTC
When I run `npm run test` I get output like this in the console:

```
 PASS  test/routing/Api.test.ts
  ● Console

    console.log
      expect(received).toEqual(expected) // deep equality
      
      - Expected  - 1
      + Received  + 1
      
      @@ -3,10 +3,10 @@
            0,
            0,
            0,
            0,
          ],
      -   "elevation": false,
      +   "elevation": undefined,
          "import_date": "some_date",
          "profiles": Array [],
          "version": "some_version",
        }

      at src/api/Api.ts:58:33
```

However, the tests still pass, so it seems like some expectations are not matched, but the test does not fail.

Also when I add a line like `throw 'something is wrong` in `compareRequestBodyAndResolve` the tests still do not fail

**Comment by karussell** [comment] 2021-05-20 22:50
To fix the error we just need to add elevation: true to the first test in Api.test.ts:

```
Promise.resolve(
                JSON.stringify({
                    elevation: false,
```

but the underlying problem that the error is not thrown is that the methods infoWithDispatch and routeWithDispatch consume the error via the Promise.catch.

In case of routeWithDispatch we could check for the sent RouteRequestFailed action in the test.
In case of infoWithDispatch we would need to sent a similar action. But probably there is a better solution to test this async stuff.

**Comment by Janekdererste** [comment] 2021-06-09 12:29
I created a draft PR. The problem was that the api is inherently async. The callback of the api call would trigger the receive method in the test method. 
```
Dispatcher.register({
            receive(action: Action) {
                expect(action instanceof InfoReceived).toBeTruthy()
                expect((action as InfoReceived).result).toEqual(expected)
            },
        })
```
The equality test would fail but the api has a catch clause 
```
infoWithDispatch() {
        this.info()
            .then(result => Dispatcher.dispatch(new InfoReceived(result)))
            .catch(e => console.log(e.message))
    }
```
This catch clause would then handle the error caused by the failed ```expect().toEqual()``` and simply print a message. The test would then finish sucessfully.

**Comment by Janekdererste** [comment] 2021-06-09 12:36
Now, I've changed things so that

1. The ```Api.infoWithDispatch``` dispatches an ```ErrorAction``` when the catch clause gets called
2. The test now has a more elaborate ```receive``` method i.e.
```
Dispatcher.register({
            receive(action: Action) {
                if (action instanceof InfoReceived) {
                    expect(action.result).toEqual(expected)
                } else if (action instanceof ErrorAction) {
                    fail(action.message)
                } else {
                    fail('unexpected action')
                }
            },
        })
```
This way the test is explicitly failed if an ```ErrorAction``` is received. Even the error message of the failed comparison is printed. because the ```ErrorAction``` wraps the error message. 

3. Additionaly the test needs to be ```async``` and the call to the tested method needs to be awaited like this to prevent the test to finish before the actions generated by the async api call are generated:
```
await new ApiImpl().infoWithDispatch()
```
I honestly don't know why one can await this method, since it doesn't return a promise but void 🤷but it works 🤷‍♀️

Is this the solution we want or does anybody have a better idea how to solve this. It feels a little complicated to me.

**Comment by karussell** [comment] 2021-06-09 14:06
> Is this the solution we want or does anybody have a better idea how to solve this? It feels a little complicated to me.

This is a reasonable approach IMO. Other solutions could be to 
1. avoid calling the catch clause for the test or 
2. provide an optional error callback which we call in infoWithDispatch if an error happens

**Comment by easbar** [comment] 2021-06-10 06:19
> I honestly don't know why one can await this method, since it doesn't return a promise but void but it works

When I tried this the await did not work actually. I had to add some extra code to make sure my expectations run after the async code in `infoWithDispatch` had finished, see here: https://github.com/graphhopper/graphhopper-maps/pull/101#discussion_r648879466

**Comment by easbar** [comment] 2021-06-10 06:22
A bit off-topic but we should probably also add the test directory (and maybe webpack config?) to the `format` script in `package.json`?

**Comment by Janekdererste** [comment] 2021-06-16 12:49
fixed with https://github.com/graphhopper/graphhopper-maps/pull/101

**Closed by Janekdererste** 2021-06-16 12:49 UTC
Labels: bug
